version: '3'
services:
  db:
    container_name: postgres-db
    image: postgres:latest
    environment:
        POSTGRES_USER: program  
        POSTGRES_PASSWORD: password
        POSTGRES_DB: timetable
    ports:
        - 5432:5432